/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e1982d8a4f4b55911b4d29f
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { CopyrightRegistrationService } from '../../services/copyright-registration.service';
// Import Models
import { CopyrightRegistration } from '../../domain/ccim_db/copyright-registration';

// START - USED SERVICES
/**
* CopyrightRegistrationService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* CopyrightRegistrationService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of CopyrightRegistration
 * @class CopyrightRegistrationListComponent
 */
@Component({
    selector: 'app-copyright-registration-list',
    templateUrl: './copyright-registration-list.component.html',
    styleUrls: ['./copyright-registration-list.component.css']
})
export class CopyrightRegistrationListComponent implements OnInit {
    list: CopyrightRegistration[];
    search: any = {};
    idSelected: string;
    constructor(
        private copyrightregistrationService: CopyrightRegistrationService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.copyrightregistrationService.list().subscribe(list => this.list = list);
    }

    /**
     * Select CopyrightRegistration to remove
     *
     * @param {string} id Id of the CopyrightRegistration to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected CopyrightRegistration
     */
    deleteItem() {
        this.copyrightregistrationService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
