/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e1982d8a4f4b55911b4d29f
*
* You will get 10% discount for each one of your friends
* 
*/
/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE copyright-registrationBaseService PLEASE EDIT ../copyright-registration.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { CopyrightRegistration } from '../../domain/ccim_db/copyright-registration';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../CopyrightRegistration.service.ts
 */

/*
 * SCHEMA DB CopyrightRegistration
 *
	{
		Audio: {
			type: 'String'
		},
		Image: {
			type: 'String'
		},
		fid: {
			type: 'Integer'
		},
		title: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Copyrightshares: {
			type: Schema.ObjectId,
			ref : "CopyrightRegistration"
		},
	}
 *
 */
@Injectable()
export class CopyrightRegistrationBaseService {

    contextUrl: string = environment.endpoint + '/copyrightregistration';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * CopyrightRegistrationService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: CopyrightRegistration): Observable<CopyrightRegistration> {
        return this.http
            .post<CopyrightRegistration>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * CopyrightRegistrationService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CopyrightRegistrationService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<CopyrightRegistration> {
        return this.http
            .get<CopyrightRegistration>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * CopyrightRegistrationService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<CopyrightRegistration[]> {
        return this.http
            .get<CopyrightRegistration[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * CopyrightRegistrationService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: CopyrightRegistration): Observable<CopyrightRegistration> {
        return this.http
            .post<CopyrightRegistration>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
