/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e1982d8a4f4b55911b4d29f
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { CopyrightRegistrationService } from '../../services/copyright-registration.service';
import { CopyrightSharesService } from '../../services/copyright-shares.service';
// Import Models
import { CopyrightRegistration } from '../../domain/ccim_db/copyright-registration';
import { CopyrightShares } from '../../domain/ccim_db/copyright-shares';

// START - USED SERVICES
/**
* CopyrightRegistrationService.create
*	@description CRUD ACTION create
*
* CopyrightRegistrationService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* CopyrightSharesService.list
*	@description CRUD ACTION list
*
* CopyrightRegistrationService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a CopyrightRegistration
 */
@Component({
    selector: 'app-copyright-registration-edit',
    templateUrl: 'copyright-registration-edit.component.html',
    styleUrls: ['copyright-registration-edit.component.css']
})
export class CopyrightRegistrationEditComponent implements OnInit {
    item: CopyrightRegistration;
    listCopyrightSharesCopyrightshares: CopyrightShares[];
    model: CopyrightRegistration;
    formValid: Boolean;

    constructor(
    private copyrightregistrationService: CopyrightRegistrationService,
    private copyrightsharesService: CopyrightSharesService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new CopyrightRegistration();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.copyrightregistrationService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
            this.copyrightsharesService.list().subscribe(list => this.listCopyrightSharesCopyrightshares = list);
        });
    }


    /**
     * Save CopyrightRegistration
     *
     * @param {boolean} formValid Form validity check
     * @param CopyrightRegistration item CopyrightRegistration to save
     */
    save(formValid: boolean, item: CopyrightRegistration): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.copyrightregistrationService.update(item).subscribe(data => this.goBack());
            } else {
                this.copyrightregistrationService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



